// Independent EliSpot v30 UI translations. Untranslated strings fall back to English.
// This does not hook or alter Spotify's own language preferences.
#import "SGLanguage.h"
#import "SGPrefs.h"

NSArray<NSString *> *SGLanguageNames(void) {
    // Native names make languages recognizable even when another language is selected.
    return @[@"System default", @"English", @"Suomi", @"Svenska",
             @"Deutsch", @"Español", @"Français"];
}

static NSString *SGCurrentLanguageCode(void) {
    NSInteger index = SGInt(SGKeyLanguage, 0);
    NSArray<NSString *> *codes = @[@"", @"en", @"fi", @"sv", @"de", @"es", @"fr"];
    if (index > 0 && index < (NSInteger)codes.count) return codes[(NSUInteger)index];
    NSString *preferred = NSLocale.preferredLanguages.firstObject ?: @"en";
    NSString *shortCode = [[preferred substringToIndex:MIN((NSUInteger)2, preferred.length)] lowercaseString];
    return [@[@"fi", @"sv", @"de", @"es", @"fr"] containsObject:shortCode] ? shortCode : @"en";
}

NSString *SGT(NSString *english) {
    if (!english.length) return english;
    NSString *code = SGCurrentLanguageCode();
    if ([code isEqualToString:@"en"]) return english;
    static NSDictionary<NSString *, NSDictionary<NSString *, NSString *> *> *translations;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        translations = @{
        @"fi": @{
            @"System default": @"Järjestelmän kieli",
            @"Language": @"Kieli",
            @"EliSpot Settings": @"EliSpot-asetukset",
            @"Appearance": @"Ulkoasu",
            @"Redesigned UI": @"Uudistettu käyttöliittymä",
            @"Needs iOS 26": @"Vaatii iOS 26:n",
            @"Accent colour": @"Korostusväri",
            @"Pick a colour": @"Valitse väri",
            @"Apple Music red": @"Apple Musicin punainen",
            @"Spotify green": @"Spotifyn vihreä",
            @"Spotify's green": @"Spotifyn vihreä",
            @"AMOLED background": @"AMOLED-tausta",
            @"Navbar": @"Navigointipalkki",
            @"Player": @"Soitin",
            @"Audio effects": @"Äänitehosteet",
            @"Live Activity": @"Live Activity",
            @"Home & Library": @"Etusivu ja kirjasto",
            @"Albums": @"Albumit",
            @"Album": @"Albumi",
            @"Artist": @"Artisti",
            @"Privacy & clutter": @"Yksityisyys ja siistiminen",
            @"Labs": @"Kokeelliset ominaisuudet",
            @"All flags": @"Kaikki ominaisuusliput",
            @"Mod": @"Modi",
            @"Gestures": @"Eleet",
            @"Lyrics": @"Sanoitukset",
            @"Blocked artists": @"Estetyt artistit",
            @"Now playing": @"Nyt soi",
            @"Now playing bar": @"Pienoissoitin",
            @"Queue & devices": @"Jono ja laitteet",
            @"Lock screen widget": @"Lukitusnäytön widget",
            @"Library": @"Kirjasto",
            @"Playlist": @"Soittolista",
            @"Playlists": @"Soittolistat",
            @"Gradient": @"Liukuväri",
            @"Download": @"Lataa",
            @"More options": @"Lisää vaihtoehtoja",
            @"More by the artist": @"Lisää artistilta",
            @"Related music videos": @"Aiheeseen liittyvät musiikkivideot",
            @"Concerts": @"Konsertit",
            @"Merch": @"Fanituotteet",
            @"You might also like": @"Saatat pitää myös näistä",
            @"What's new in v30": @"Mitä uutta v30:ssä",
            @"What's new": @"Mitä uutta",
            @"Version": @"Versio",
            @"Website": @"Verkkosivusto",
            @"Welcome tour": @"Esittely",
            @"Export settings": @"Vie asetukset",
            @"Import settings": @"Tuo asetukset",
            @"Reset all settings": @"Palauta kaikki asetukset",
            @"GitHub": @"GitHub",
            @"Changes apply after you restart Spotify.": @"Muutokset tulevat voimaan Spotifyn uudelleenkäynnistyksen jälkeen.",
            @"EliSpot settings only; Spotify uses its own language settings.": @"Vain EliSpotin asetuksiin. Spotify käyttää omia kieliasetuksiaan.",
            @"Hide track artists": @"Piilota kappaleiden artistit",
            @"Track list": @"Kappalelista",
            @"Hide the subtitle below songs on album pages.": @"Piilota artistiteksti albumisivujen kappaleista.",
            @"Restart Spotify": @"Käynnistä Spotify uudelleen",
            @"Later": @"Myöhemmin",
            @"Restart now": @"Käynnistä nyt",
            @"Cancel": @"Peruuta",
            @"OK": @"OK",
            @"On": @"Päällä",
            @"Off": @"Pois",
            @"Display": @"Näyttö",
            @"Sources": @"Lähteet",
            @"Show": @"Näytä",
            @"Hide": @"Piilota",
            @"Search": @"Haku",
            @"Settings": @"Asetukset",
            @"Sound": @"Ääni",
            @"Account": @"Tili",
            @"Theme": @"Teema",
            @"Custom": @"Mukautettu",
            @"Choose a preset or your own colour. Restart Spotify to apply.": @"Valitse valmis väri tai oma väri. Käynnistä Spotify uudelleen.",
            @"Both looks": @"Molemmat ulkoasut",
            @"Redesign": @"Uudistettu ulkoasu",
            @"In progress": @"Työn alla",
            @"Added so far": @"Lisätty tähän mennessä",
            @"Planned": @"Suunnitteilla",
            @"0.50-style player and lyrics": @"0.50-tyylinen soitin ja sanoitukset",
            @"Tab bar and animated artwork": @"Välilehtipalkki ja animoidut kansikuvat",
            @"Home": @"Etusivu",
            @"Colour": @"Väri",
            @"Strength": @"Voimakkuus",
            @"Height": @"Korkeus",
            @"Hide on Home": @"Piilota etusivulta",
            @"Navigation bar": @"Navigointipalkki",
            @"About this switch": @"Tietoa tästä kytkimestä",
            @"Overridden by another setting": @"Toinen asetus ohittaa tämän",
            @"Another switch is forcing this flag, so the row shows what it forces instead of taking a value of its own.": @"Toinen kytkin määrää tämän ominaisuuden arvon.",
            @"Open GitHub": @"Avaa GitHub",
            @"Header": @"Ylätunniste",
            @"Hide in the header": @"Piilota ylätunnisteesta",
            @"Hide on the page": @"Piilota sivulta",
            @"Artwork background": @"Kansikuvan tausta",
            @"Add to library": @"Lisää kirjastoon",
            @"Browse": @"Selaa",
            @"Presets": @"Esiasetukset",
            @"Sort artists by recently updated": @"Lajittele artistit viimeksi päivitetyn mukaan",
            @"Scroll to refresh": @"Päivitä vierittämällä",
            @"Mod Settings": @"Modin asetukset",
            @"Hide social proof": @"Piilota sosiaalinen suosio",
            @"Audio": @"Ääni",
            @"Current language": @"Nykyinen kieli",
            @"Automatic": @"Automaattinen",
            @"Native look": @"Perinteinen ulkoasu",
            @"Artists": @"Artistit",
            @"Sections": @"Osiot",
            @"Hide music videos": @"Piilota musiikkivideot",
            @"Remove video shelves from redesigned artist pages.": @"Piilota musiikkivideoiden osiot uudistetuilta artistisivuilta.",
            @"Extra sections": @"Lisäosiot",
            @"Show extra album sections": @"Näytä albumin lisäosiot",
            @"Show album recommendations, videos and other sections below the tracks.": @"Näytä suositukset, musiikkivideot ja muut osiot kappalelistan alla.",
            @"Animated cover motion": @"Animoitu kansiliike",
            @"Moves still cover art, not original video. Respects Reduce Motion and Low Power Mode.": @"Liikuttaa tavallista kansikuvaa, ei alkuperäistä videota. Noudattaa Vähennä liikettä -asetusta ja virransäästötilaa.",
            @"Apple Music-inspired look": @"Apple Music -tyylinen ulkoasu",
            @"Use the redesigned player, red controls, motion field and animated still covers.": @"Uudistettu soitin, punaiset painikkeet, liikkuva tausta ja animoidut kansikuvat.",
            @"Enable redesigned UI, red accents, moving background and animated still covers? Restart Spotify to apply. This is not original Apple Music video artwork.": @"Otetaanko käyttöön uudistettu ulkoasu, punainen korostusväri, liikkuva tausta ja animoidut kansikuvat? Muutokset tulevat voimaan Spotifyn käynnistyessä uudelleen. Nämä eivät ole Apple Musicin alkuperäisiä videokansia.",
            @"Active": @"Käytössä",
            @"Apply": @"Ota käyttöön",
            @"Sound processing": @"Äänenkäsittely",
            @"Playback speed": @"Toistonopeus",
            @"Pitch": @"Sävelkorkeus",
            @"Changes playback tempo when available.": @"Muuttaa toistonopeutta, kun ominaisuus on käytettävissä.",
            @"Change the sound by semitones.": @"Muuttaa sävelkorkeutta puolisävelaskelein.",
            @"Waiting for audio": @"Odottaa ääntä",
            @"Available": @"Käytettävissä",
            @"Reset sound changes": @"Palauta alkuperäinen ääni",
            @"Advanced effects": @"Lisä-ääniefektit",
            @"JamesDSP equalizer / bass / reverb": @"JamesDSP-taajuuskorjain, basso ja kaiku",
            @"Mac build only": @"Vain Mac-buildissa",
            @"Speed, pitch & haptics": @"Nopeus, sävelkorkeus ja värinä",
            @"These controls use EliSpot's built-in audio unit. Start playback before opening this page. Availability depends on the device and playback output.": @"Säätimet käyttävät EliSpotin sisäistä äänimoottoria. Käynnistä musiikki ennen sivun avaamista. Toimivuus riippuu laitteesta ja äänilähdöstä.",
            @"Ubuntu/WSL does not build the JamesDSP engine yet. The effects listed above are real controls; the JamesDSP effects are not enabled.": @"Ubuntu/WSL ei vielä rakenna JamesDSP-moottoria. Yllä olevat säätimet ovat toimivia silloin, kun äänimoottori tukee niitä. JamesDSP-efektit eivät ole käytössä.",
            @"Choose a Spotify, AMOLED, Apple Music-inspired or coloured look.": @"Valitse Spotify-, AMOLED-, Apple Music -tyylinen tai värillinen ulkoasu.",
            @"Pick a look. Use Accent colour for a custom colour. Changes require a Spotify restart.": @"Valitse ulkoasu. Oman värin voit valita Korostusväri-asetuksesta. Käynnistä Spotify uudelleen.",
            @"Spotify default": @"Spotifyn alkuperäinen",
            @"AMOLED black": @"AMOLED-musta",
            @"Apple Music style": @"Apple Music -tyyli",
            @"Midnight blue": @"Keskiyönsininen",
            @"Violet": @"Violetti",
            @"1 source": @"1 lähde",
            @"%lu sources": @"%lu lähdettä",
            @"Lyrics where Spotify has none": @"Sanoitukset myös puuttuviin kappaleisiin",
            @"Search your selected sources for missing lyrics.": @"Etsi puuttuvia sanoituksia valituista lähteistä.",
            @"A source must provide lyrics for the track. Turning this on cannot guarantee lyrics for every song. Restart Spotify after changing this option or the sources.": @"Sanoitukset näytetään vain, jos jokin lähde löytää ne. Valinta ei takaa sanoituksia joka kappaleelle. Käynnistä Spotify uudelleen asetuksen tai lähteiden muuttamisen jälkeen.",
            @"No lyrics sources": @"Ei sanoituslähteitä",
            @"Enable at least one lyrics source, then restart Spotify.": @"Ota käyttöön vähintään yksi sanoituslähde ja käynnistä Spotify uudelleen.",
            @"Lyrics only appear when a selected provider finds them. Restart Spotify after changing these settings.": @"Sanoitukset näkyvät vain, jos valittu lähde löytää ne. Käynnistä Spotify uudelleen muutosten jälkeen.",
            @"Test lyrics for current song": @"Testaa nykyisen kappaleen sanoitukset",
            @"Check whether your enabled sources can find lyrics for the playing track.": @"Tarkista, löytävätkö käytössä olevat lähteet soivan kappaleen sanoitukset.",
            @"Lyrics source test": @"Sanoituslähteiden testi",
            @"Play a song first, then try again.": @"Aloita kappaleen toisto ja yritä uudelleen.",
            @"Enable at least one source in Sources, then restart Spotify.": @"Ota käyttöön ainakin yksi lähde Lähteet-sivulta ja käynnistä Spotify uudelleen.",
            @"Found lyrics from %@.": @"Sanoitukset löytyivät lähteestä %@.",
            @"No lyrics found for this track from the selected sources.": @"Valitut lähteet eivät löytäneet sanoituksia tälle kappaleelle.",
            @"Show source": @"Näytä lähde",
            @"Simulate word timing": @"Jäljitelty sanakohtainen ajoitus",
            @"Text sizes": @"Tekstikoot",
            @"Translation language": @"Käännöskieli",
            @"Lock screen lyrics": @"Lukitusnäytön sanoitukset",
            @"Current line in place of the artist": @"Nykyinen sanoitusrivi artistin nimen tilalla",
            @"Any": @"Mikä tahansa"
        },
        @"sv": @{
            @"System default": @"Systemets språk",
            @"Language": @"Språk",
            @"EliSpot Settings": @"EliSpot-inställningar",
            @"Appearance": @"Utseende",
            @"Redesigned UI": @"Omdesignat gränssnitt",
            @"Needs iOS 26": @"Kräver iOS 26",
            @"Accent colour": @"Accentfärg",
            @"Pick a colour": @"Välj färg",
            @"Apple Music red": @"Apple Music-röd",
            @"Spotify green": @"Spotify-grön",
            @"AMOLED background": @"AMOLED-bakgrund",
            @"Navbar": @"Navigeringsfält",
            @"Player": @"Spelare",
            @"Audio effects": @"Ljudeffekter",
            @"Live Activity": @"Liveaktivitet",
            @"Home & Library": @"Hem och bibliotek",
            @"Albums": @"Album",
            @"Album": @"Album",
            @"Artist": @"Artist",
            @"Privacy & clutter": @"Integritet och förenkling",
            @"Labs": @"Experiment",
            @"All flags": @"Alla funktionsflaggor",
            @"Mod": @"Modd",
            @"Gestures": @"Gester",
            @"Lyrics": @"Låttexter",
            @"Blocked artists": @"Blockerade artister",
            @"Now playing": @"Spelas nu",
            @"Now playing bar": @"Minispelare",
            @"Queue & devices": @"Kö och enheter",
            @"Lock screen widget": @"Låsskärmswidget",
            @"Library": @"Bibliotek",
            @"Playlist": @"Spellista",
            @"Playlists": @"Spellistor",
            @"Gradient": @"Färgövergång",
            @"Download": @"Ladda ned",
            @"More options": @"Fler alternativ",
            @"What's new in v30": @"Nyheter i v30",
            @"What's new": @"Nyheter",
            @"Version": @"Version",
            @"Website": @"Webbplats",
            @"Welcome tour": @"Introduktion",
            @"Export settings": @"Exportera inställningar",
            @"Import settings": @"Importera inställningar",
            @"Reset all settings": @"Återställ alla inställningar",
            @"Changes apply after you restart Spotify.": @"Ändringarna gäller efter att Spotify har startats om.",
            @"EliSpot settings only; Spotify uses its own language settings.": @"Endast EliSpot-inställningar. Spotify har egna språkinställningar.",
            @"Hide track artists": @"Dölj låtartister",
            @"Track list": @"Låtlista",
            @"Hide the subtitle below songs on album pages.": @"Dölj artisttexten under låtar på albumsidor.",
            @"Restart Spotify": @"Starta om Spotify",
            @"Later": @"Senare",
            @"Restart now": @"Starta om nu",
            @"Cancel": @"Avbryt",
            @"OK": @"OK",
            @"On": @"På",
            @"Off": @"Av",
            @"Display": @"Visning",
            @"Sources": @"Källor",
            @"Show": @"Visa",
            @"Hide": @"Dölj",
            @"Search": @"Sök",
            @"Settings": @"Inställningar",
            @"Choose a preset or your own colour. Restart Spotify to apply.": @"Välj en färg eller skapa en egen. Starta om Spotify.",
            @"Both looks": @"Båda utseendena",
            @"Redesign": @"Omdesignad",
            @"In progress": @"Pågår",
            @"Added so far": @"Tillagt hittills",
            @"Planned": @"Planerat",
            @"Home": @"Hem",
            @"Colour": @"Färg",
            @"Strength": @"Styrka",
            @"Height": @"Höjd",
            @"Hide on Home": @"Dölj på startsidan",
            @"About this switch": @"Om detta reglage",
            @"Open GitHub": @"Öppna GitHub",
            @"More by the artist": @"Mer av artisten",
            @"Related music videos": @"Relaterade musikvideor",
            @"Concerts": @"Konserter",
            @"Merch": @"Produkter",
            @"You might also like": @"Du kanske också gillar",
            @"Header": @"Sidhuvud",
            @"Hide in the header": @"Dölj i sidhuvudet",
            @"Hide on the page": @"Dölj på sidan",
            @"Artwork background": @"Omslagsbakgrund",
            @"Add to library": @"Lägg till i biblioteket",
            @"Tab bar and animated artwork": @"Flikfält och animerade omslag",
            @"0.50-style player and lyrics": @"0.50-liknande spelare och låttexter",
            @"Overridden by another setting": @"Åsidosatt av en annan inställning",
            @"Artists": @"Artister",
            @"Sections": @"Avsnitt",
            @"Hide music videos": @"Dölj musikvideor",
            @"Remove video shelves from redesigned artist pages.": @"Dölj musikvideor från omdesignade artistsidor.",
            @"Extra sections": @"Extra avsnitt",
            @"Show extra album sections": @"Visa extra albumavsnitt",
            @"Show album recommendations, videos and other sections below the tracks.": @"Visa rekommendationer, videor och andra avsnitt under låtarna.",
            @"Animated cover motion": @"Animerad omslagsrörelse",
            @"Moves still cover art, not original video. Respects Reduce Motion and Low Power Mode.": @"Ger stillbilder en mjuk rörelse, inte originalvideo. Respekterar Minska rörelse och strömsparläge.",
            @"Apple Music-inspired look": @"Apple Music-inspirerat utseende",
            @"Use the redesigned player, red controls, motion field and animated still covers.": @"Ny spelare, röda reglage, rörlig bakgrund och animerade omslag.",
            @"Enable redesigned UI, red accents, moving background and animated still covers? Restart Spotify to apply. This is not original Apple Music video artwork.": @"Aktivera ny design, röda reglage, rörlig bakgrund och animerade omslag? Starta om Spotify. Det är inte ursprungliga Apple Music-videor.",
            @"Active": @"Aktiv",
            @"Apply": @"Använd",
            @"Sound processing": @"Ljudbearbetning",
            @"Playback speed": @"Uppspelningshastighet",
            @"Pitch": @"Tonhöjd",
            @"Changes playback tempo when available.": @"Ändrar tempot när funktionen stöds.",
            @"Change the sound by semitones.": @"Ändra tonhöjden i halvtoner.",
            @"Waiting for audio": @"Väntar på ljud",
            @"Available": @"Tillgänglig",
            @"Reset sound changes": @"Återställ ljudet",
            @"Advanced effects": @"Avancerade effekter",
            @"JamesDSP equalizer / bass / reverb": @"JamesDSP-equalizer, bas och reverb",
            @"Mac build only": @"Endast Mac-version",
            @"Speed, pitch & haptics": @"Hastighet, tonhöjd och haptik",
            @"Theme": @"Tema",
            @"Spotify default": @"Spotify standard",
            @"AMOLED black": @"AMOLED-svart",
            @"Apple Music style": @"Apple Music-stil",
            @"Midnight blue": @"Midnattsblå",
            @"Violet": @"Violett",
            @"1 source": @"1 källa",
            @"%lu sources": @"%lu källor",
            @"Lyrics where Spotify has none": @"Låttexter där Spotify saknar dem",
            @"Search your selected sources for missing lyrics.": @"Sök efter saknade låttexter i valda källor.",
            @"Test lyrics for current song": @"Testa låttext för aktuell låt",
            @"Lyrics source test": @"Test av låttextkällor",
            @"No lyrics sources": @"Inga låttextkällor",
            @"No lyrics found for this track from the selected sources.": @"De valda källorna hittade ingen låttext för den här låten.",
            @"Show source": @"Visa källa",
            @"Simulate word timing": @"Simulera ordtiming",
            @"Text sizes": @"Textstorlekar",
            @"Translation language": @"Översättningsspråk"
        },
        @"de": @{
            @"System default": @"Systemsprache",
            @"Language": @"Sprache",
            @"EliSpot Settings": @"EliSpot-Einstellungen",
            @"Appearance": @"Darstellung",
            @"Redesigned UI": @"Neues Design",
            @"Needs iOS 26": @"Benötigt iOS 26",
            @"Accent colour": @"Akzentfarbe",
            @"Pick a colour": @"Farbe auswählen",
            @"Apple Music red": @"Apple-Music-Rot",
            @"Spotify green": @"Spotify-Grün",
            @"AMOLED background": @"AMOLED-Hintergrund",
            @"Navbar": @"Navigationsleiste",
            @"Player": @"Player",
            @"Audio effects": @"Audioeffekte",
            @"Live Activity": @"Live-Aktivität",
            @"Home & Library": @"Startseite und Bibliothek",
            @"Albums": @"Alben",
            @"Album": @"Album",
            @"Artist": @"Künstler",
            @"Privacy & clutter": @"Datenschutz und Übersicht",
            @"Labs": @"Experimente",
            @"All flags": @"Alle Funktionsflags",
            @"Mod": @"Mod",
            @"Gestures": @"Gesten",
            @"Lyrics": @"Songtexte",
            @"Blocked artists": @"Blockierte Künstler",
            @"Now playing": @"Aktueller Titel",
            @"Now playing bar": @"Miniplayer",
            @"Queue & devices": @"Warteschlange und Geräte",
            @"Lock screen widget": @"Sperrbildschirm-Widget",
            @"Library": @"Bibliothek",
            @"Playlist": @"Playlist",
            @"Playlists": @"Playlists",
            @"Gradient": @"Farbverlauf",
            @"Download": @"Herunterladen",
            @"More options": @"Weitere Optionen",
            @"What's new in v30": @"Neu in v30",
            @"What's new": @"Neuigkeiten",
            @"Version": @"Version",
            @"Website": @"Webseite",
            @"Welcome tour": @"Einführung",
            @"Export settings": @"Einstellungen exportieren",
            @"Import settings": @"Einstellungen importieren",
            @"Reset all settings": @"Alle Einstellungen zurücksetzen",
            @"Changes apply after you restart Spotify.": @"Änderungen werden nach einem Neustart von Spotify wirksam.",
            @"EliSpot settings only; Spotify uses its own language settings.": @"Nur für EliSpot-Einstellungen. Spotify hat eigene Spracheinstellungen.",
            @"Hide track artists": @"Titelkünstler ausblenden",
            @"Track list": @"Titelliste",
            @"Hide the subtitle below songs on album pages.": @"Künstler unter Titeln auf Albumseiten ausblenden.",
            @"Restart Spotify": @"Spotify neu starten",
            @"Later": @"Später",
            @"Restart now": @"Jetzt neu starten",
            @"Cancel": @"Abbrechen",
            @"OK": @"OK",
            @"On": @"An",
            @"Off": @"Aus",
            @"Display": @"Anzeige",
            @"Sources": @"Quellen",
            @"Show": @"Anzeigen",
            @"Hide": @"Ausblenden",
            @"Search": @"Suche",
            @"Settings": @"Einstellungen",
            @"Choose a preset or your own colour. Restart Spotify to apply.": @"Wähle eine Farbe oder einen eigenen Farbton. Spotify neu starten.",
            @"Both looks": @"Beide Designs",
            @"Redesign": @"Neues Design",
            @"In progress": @"In Arbeit",
            @"Added so far": @"Bereits hinzugefügt",
            @"Planned": @"Geplant",
            @"Home": @"Startseite",
            @"Colour": @"Farbe",
            @"Strength": @"Stärke",
            @"Height": @"Höhe",
            @"Hide on Home": @"Auf Startseite ausblenden",
            @"About this switch": @"Über diesen Schalter",
            @"Open GitHub": @"GitHub öffnen",
            @"More by the artist": @"Mehr vom Künstler",
            @"Related music videos": @"Ähnliche Musikvideos",
            @"Concerts": @"Konzerte",
            @"Merch": @"Fanartikel",
            @"You might also like": @"Das könnte dir auch gefallen",
            @"Header": @"Kopfbereich",
            @"Hide in the header": @"Im Kopfbereich ausblenden",
            @"Hide on the page": @"Auf der Seite ausblenden",
            @"Artwork background": @"Cover-Hintergrund",
            @"Add to library": @"Zur Bibliothek hinzufügen",
            @"Tab bar and animated artwork": @"Tab-Leiste und animierte Cover",
            @"0.50-style player and lyrics": @"0.50-Player und Songtexte",
            @"Overridden by another setting": @"Durch andere Einstellung überschrieben",
            @"Artists": @"Künstler",
            @"Sections": @"Abschnitte",
            @"Hide music videos": @"Musikvideos ausblenden",
            @"Remove video shelves from redesigned artist pages.": @"Musikvideos auf neu gestalteten Künstlerseiten ausblenden.",
            @"Extra sections": @"Weitere Abschnitte",
            @"Show extra album sections": @"Weitere Albumabschnitte anzeigen",
            @"Show album recommendations, videos and other sections below the tracks.": @"Empfehlungen, Videos und weitere Abschnitte unter den Titeln anzeigen.",
            @"Animated cover motion": @"Animierte Cover-Bewegung",
            @"Moves still cover art, not original video. Respects Reduce Motion and Low Power Mode.": @"Bewegt Standbilder sanft, kein Originalvideo. Berücksichtigt Bewegung reduzieren und Stromsparmodus.",
            @"Apple Music-inspired look": @"Apple-Music-inspiriertes Design",
            @"Use the redesigned player, red controls, motion field and animated still covers.": @"Neuer Player, rote Bedienelemente, bewegter Hintergrund und animierte Cover.",
            @"Enable redesigned UI, red accents, moving background and animated still covers? Restart Spotify to apply. This is not original Apple Music video artwork.": @"Neues Design mit Rot, bewegtem Hintergrund und animierten Covern aktivieren? Spotify neu starten. Keine Originalvideos von Apple Music.",
            @"Active": @"Aktiv",
            @"Apply": @"Anwenden",
            @"Sound processing": @"Klangbearbeitung",
            @"Playback speed": @"Wiedergabegeschwindigkeit",
            @"Pitch": @"Tonhöhe",
            @"Changes playback tempo when available.": @"Ändert das Tempo, wenn verfügbar.",
            @"Change the sound by semitones.": @"Ändert die Tonhöhe in Halbtönen.",
            @"Waiting for audio": @"Warte auf Audio",
            @"Available": @"Verfügbar",
            @"Reset sound changes": @"Klang zurücksetzen",
            @"Advanced effects": @"Erweiterte Effekte",
            @"JamesDSP equalizer / bass / reverb": @"JamesDSP-Equalizer, Bass und Hall",
            @"Mac build only": @"Nur im Mac-Build",
            @"Speed, pitch & haptics": @"Tempo, Tonhöhe und Haptik",
            @"Theme": @"Design",
            @"Spotify default": @"Spotify-Standard",
            @"AMOLED black": @"AMOLED-Schwarz",
            @"Apple Music style": @"Apple-Music-Stil",
            @"Midnight blue": @"Mitternachtsblau",
            @"Violet": @"Violett",
            @"1 source": @"1 Quelle",
            @"%lu sources": @"%lu Quellen",
            @"Lyrics where Spotify has none": @"Songtexte, wenn Spotify keine hat",
            @"Search your selected sources for missing lyrics.": @"Fehlende Texte in ausgewählten Quellen suchen.",
            @"Test lyrics for current song": @"Songtext für aktuellen Titel testen",
            @"Lyrics source test": @"Songtextquellen-Test",
            @"No lyrics sources": @"Keine Songtextquellen",
            @"No lyrics found for this track from the selected sources.": @"Die ausgewählten Quellen haben keinen Text für diesen Titel gefunden.",
            @"Show source": @"Quelle anzeigen",
            @"Simulate word timing": @"Wort-Timing simulieren",
            @"Text sizes": @"Textgrößen",
            @"Translation language": @"Übersetzungssprache"
        },
        @"es": @{
            @"System default": @"Idioma del sistema",
            @"Language": @"Idioma",
            @"EliSpot Settings": @"Ajustes de EliSpot",
            @"Appearance": @"Apariencia",
            @"Redesigned UI": @"Interfaz rediseñada",
            @"Needs iOS 26": @"Requiere iOS 26",
            @"Accent colour": @"Color de acento",
            @"Pick a colour": @"Elegir color",
            @"Apple Music red": @"Rojo de Apple Music",
            @"Spotify green": @"Verde de Spotify",
            @"AMOLED background": @"Fondo AMOLED",
            @"Navbar": @"Barra de navegación",
            @"Player": @"Reproductor",
            @"Audio effects": @"Efectos de audio",
            @"Live Activity": @"Actividad en vivo",
            @"Home & Library": @"Inicio y biblioteca",
            @"Albums": @"Álbumes",
            @"Album": @"Álbum",
            @"Artist": @"Artista",
            @"Privacy & clutter": @"Privacidad y limpieza",
            @"Labs": @"Funciones experimentales",
            @"All flags": @"Todas las opciones",
            @"Mod": @"Mod",
            @"Gestures": @"Gestos",
            @"Lyrics": @"Letras",
            @"Blocked artists": @"Artistas bloqueados",
            @"Now playing": @"Reproduciendo",
            @"Now playing bar": @"Minirreproductor",
            @"Queue & devices": @"Cola y dispositivos",
            @"Lock screen widget": @"Widget de pantalla bloqueada",
            @"Library": @"Biblioteca",
            @"Playlist": @"Lista de reproducción",
            @"Playlists": @"Listas de reproducción",
            @"Gradient": @"Degradado",
            @"Download": @"Descargar",
            @"More options": @"Más opciones",
            @"What's new in v30": @"Novedades de v30",
            @"What's new": @"Novedades",
            @"Version": @"Versión",
            @"Website": @"Sitio web",
            @"Welcome tour": @"Introducción",
            @"Export settings": @"Exportar ajustes",
            @"Import settings": @"Importar ajustes",
            @"Reset all settings": @"Restablecer todos los ajustes",
            @"Changes apply after you restart Spotify.": @"Los cambios se aplican al reiniciar Spotify.",
            @"EliSpot settings only; Spotify uses its own language settings.": @"Solo los ajustes de EliSpot. Spotify tiene sus propios ajustes de idioma.",
            @"Hide track artists": @"Ocultar artistas de las canciones",
            @"Track list": @"Lista de canciones",
            @"Hide the subtitle below songs on album pages.": @"Oculta los artistas debajo de las canciones en los álbumes.",
            @"Restart Spotify": @"Reiniciar Spotify",
            @"Later": @"Más tarde",
            @"Restart now": @"Reiniciar ahora",
            @"Cancel": @"Cancelar",
            @"OK": @"Aceptar",
            @"On": @"Activado",
            @"Off": @"Desactivado",
            @"Display": @"Pantalla",
            @"Sources": @"Fuentes",
            @"Show": @"Mostrar",
            @"Hide": @"Ocultar",
            @"Search": @"Buscar",
            @"Settings": @"Ajustes",
            @"Choose a preset or your own colour. Restart Spotify to apply.": @"Elige un color o personaliza uno. Reinicia Spotify.",
            @"Both looks": @"Ambos estilos",
            @"Redesign": @"Rediseño",
            @"In progress": @"En desarrollo",
            @"Added so far": @"Añadido hasta ahora",
            @"Planned": @"Previsto",
            @"Home": @"Inicio",
            @"Colour": @"Color",
            @"Strength": @"Intensidad",
            @"Height": @"Altura",
            @"Hide on Home": @"Ocultar en Inicio",
            @"About this switch": @"Sobre este interruptor",
            @"Open GitHub": @"Abrir GitHub",
            @"More by the artist": @"Más del artista",
            @"Related music videos": @"Vídeos musicales relacionados",
            @"Concerts": @"Conciertos",
            @"Merch": @"Productos",
            @"You might also like": @"También te puede gustar",
            @"Header": @"Encabezado",
            @"Hide in the header": @"Ocultar en el encabezado",
            @"Hide on the page": @"Ocultar en la página",
            @"Artwork background": @"Fondo de la portada",
            @"Add to library": @"Añadir a la biblioteca",
            @"Tab bar and animated artwork": @"Pestañas y portadas animadas",
            @"0.50-style player and lyrics": @"Reproductor y letras estilo 0.50",
            @"Overridden by another setting": @"Anulado por otro ajuste",
            @"Artists": @"Artistas",
            @"Sections": @"Secciones",
            @"Hide music videos": @"Ocultar vídeos musicales",
            @"Remove video shelves from redesigned artist pages.": @"Ocultar los vídeos musicales en las páginas rediseñadas de artistas.",
            @"Extra sections": @"Secciones adicionales",
            @"Show extra album sections": @"Mostrar más secciones del álbum",
            @"Show album recommendations, videos and other sections below the tracks.": @"Mostrar recomendaciones, vídeos y otras secciones debajo de las canciones.",
            @"Animated cover motion": @"Movimiento animado de portadas",
            @"Moves still cover art, not original video. Respects Reduce Motion and Low Power Mode.": @"Mueve suavemente las portadas fijas; no es vídeo original. Respeta Reducir movimiento y Ahorro de energía.",
            @"Apple Music-inspired look": @"Estilo inspirado en Apple Music",
            @"Use the redesigned player, red controls, motion field and animated still covers.": @"Reproductor renovado, controles rojos, fondo animado y portadas con movimiento.",
            @"Enable redesigned UI, red accents, moving background and animated still covers? Restart Spotify to apply. This is not original Apple Music video artwork.": @"¿Activar el diseño nuevo, rojo, fondo animado y portadas en movimiento? Reinicia Spotify. No son vídeos originales de Apple Music.",
            @"Active": @"Activo",
            @"Apply": @"Aplicar",
            @"Sound processing": @"Procesamiento de audio",
            @"Playback speed": @"Velocidad de reproducción",
            @"Pitch": @"Tono",
            @"Changes playback tempo when available.": @"Cambia el tempo cuando es posible.",
            @"Change the sound by semitones.": @"Cambia el tono en semitonos.",
            @"Waiting for audio": @"Esperando audio",
            @"Available": @"Disponible",
            @"Reset sound changes": @"Restablecer el sonido",
            @"Advanced effects": @"Efectos avanzados",
            @"JamesDSP equalizer / bass / reverb": @"Ecualizador, graves y reverberación JamesDSP",
            @"Mac build only": @"Solo versión Mac",
            @"Speed, pitch & haptics": @"Velocidad, tono y vibración",
            @"Theme": @"Tema",
            @"Spotify default": @"Spotify original",
            @"AMOLED black": @"Negro AMOLED",
            @"Apple Music style": @"Estilo Apple Music",
            @"Midnight blue": @"Azul medianoche",
            @"Violet": @"Violeta",
            @"1 source": @"1 fuente",
            @"%lu sources": @"%lu fuentes",
            @"Lyrics where Spotify has none": @"Letras cuando Spotify no tiene",
            @"Search your selected sources for missing lyrics.": @"Buscar letras en las fuentes seleccionadas.",
            @"Test lyrics for current song": @"Probar letras de la canción actual",
            @"Lyrics source test": @"Prueba de fuentes de letras",
            @"No lyrics sources": @"No hay fuentes de letras",
            @"No lyrics found for this track from the selected sources.": @"Las fuentes seleccionadas no encontraron letras para esta canción.",
            @"Show source": @"Mostrar fuente",
            @"Simulate word timing": @"Simular tiempo por palabra",
            @"Text sizes": @"Tamaños de texto",
            @"Translation language": @"Idioma de traducción"
        },
        @"fr": @{
            @"System default": @"Langue du système",
            @"Language": @"Langue",
            @"EliSpot Settings": @"Réglages EliSpot",
            @"Appearance": @"Apparence",
            @"Redesigned UI": @"Nouvelle interface",
            @"Needs iOS 26": @"Nécessite iOS 26",
            @"Accent colour": @"Couleur d’accent",
            @"Pick a colour": @"Choisir une couleur",
            @"Apple Music red": @"Rouge Apple Music",
            @"Spotify green": @"Vert Spotify",
            @"AMOLED background": @"Fond AMOLED",
            @"Navbar": @"Barre de navigation",
            @"Player": @"Lecteur",
            @"Audio effects": @"Effets audio",
            @"Live Activity": @"Activité en direct",
            @"Home & Library": @"Accueil et bibliothèque",
            @"Albums": @"Albums",
            @"Album": @"Album",
            @"Artist": @"Artiste",
            @"Privacy & clutter": @"Confidentialité et affichage",
            @"Labs": @"Fonctions expérimentales",
            @"All flags": @"Tous les indicateurs",
            @"Mod": @"Mod",
            @"Gestures": @"Gestes",
            @"Lyrics": @"Paroles",
            @"Blocked artists": @"Artistes bloqués",
            @"Now playing": @"Lecture en cours",
            @"Now playing bar": @"Mini-lecteur",
            @"Queue & devices": @"File d’attente et appareils",
            @"Lock screen widget": @"Widget d’écran verrouillé",
            @"Library": @"Bibliothèque",
            @"Playlist": @"Playlist",
            @"Playlists": @"Playlists",
            @"Gradient": @"Dégradé",
            @"Download": @"Télécharger",
            @"More options": @"Plus d’options",
            @"What's new in v30": @"Nouveautés de v30",
            @"What's new": @"Nouveautés",
            @"Version": @"Version",
            @"Website": @"Site web",
            @"Welcome tour": @"Présentation",
            @"Export settings": @"Exporter les réglages",
            @"Import settings": @"Importer les réglages",
            @"Reset all settings": @"Réinitialiser tous les réglages",
            @"Changes apply after you restart Spotify.": @"Les changements s’appliquent après le redémarrage de Spotify.",
            @"EliSpot settings only; Spotify uses its own language settings.": @"Réglages EliSpot uniquement. Spotify possède ses propres réglages de langue.",
            @"Hide track artists": @"Masquer les artistes des titres",
            @"Track list": @"Liste des titres",
            @"Hide the subtitle below songs on album pages.": @"Masquer l’artiste sous chaque titre des albums.",
            @"Restart Spotify": @"Redémarrer Spotify",
            @"Later": @"Plus tard",
            @"Restart now": @"Redémarrer maintenant",
            @"Cancel": @"Annuler",
            @"OK": @"OK",
            @"On": @"Activé",
            @"Off": @"Désactivé",
            @"Display": @"Affichage",
            @"Sources": @"Sources",
            @"Show": @"Afficher",
            @"Hide": @"Masquer",
            @"Search": @"Rechercher",
            @"Settings": @"Réglages",
            @"Choose a preset or your own colour. Restart Spotify to apply.": @"Choisissez une couleur ou créez la vôtre. Redémarrez Spotify.",
            @"Both looks": @"Les deux styles",
            @"Redesign": @"Nouvelle interface",
            @"In progress": @"En cours",
            @"Added so far": @"Déjà ajouté",
            @"Planned": @"Prévu",
            @"Home": @"Accueil",
            @"Colour": @"Couleur",
            @"Strength": @"Intensité",
            @"Height": @"Hauteur",
            @"Hide on Home": @"Masquer sur l’accueil",
            @"About this switch": @"À propos de ce réglage",
            @"Open GitHub": @"Ouvrir GitHub",
            @"More by the artist": @"Plus de cet artiste",
            @"Related music videos": @"Vidéos musicales associées",
            @"Concerts": @"Concerts",
            @"Merch": @"Produits dérivés",
            @"You might also like": @"Vous pourriez aussi aimer",
            @"Header": @"En-tête",
            @"Hide in the header": @"Masquer dans l’en-tête",
            @"Hide on the page": @"Masquer sur la page",
            @"Artwork background": @"Fond de la pochette",
            @"Add to library": @"Ajouter à la bibliothèque",
            @"Tab bar and animated artwork": @"Onglets et pochettes animées",
            @"0.50-style player and lyrics": @"Lecteur et paroles style 0.50",
            @"Overridden by another setting": @"Remplacé par un autre réglage",
            @"Artists": @"Artistes",
            @"Sections": @"Sections",
            @"Hide music videos": @"Masquer les clips musicaux",
            @"Remove video shelves from redesigned artist pages.": @"Masquer les clips sur les pages d'artistes repensées.",
            @"Extra sections": @"Sections supplémentaires",
            @"Show extra album sections": @"Afficher les autres sections de l'album",
            @"Show album recommendations, videos and other sections below the tracks.": @"Afficher les recommandations, vidéos et autres sections sous les titres.",
            @"Animated cover motion": @"Mouvement animé des pochettes",
            @"Moves still cover art, not original video. Respects Reduce Motion and Low Power Mode.": @"Anime doucement les pochettes fixes, sans vidéo originale. Respecte Réduire les animations et le mode économie d’énergie.",
            @"Apple Music-inspired look": @"Style inspiré d’Apple Music",
            @"Use the redesigned player, red controls, motion field and animated still covers.": @"Nouveau lecteur, commandes rouges, fond animé et pochettes en mouvement.",
            @"Enable redesigned UI, red accents, moving background and animated still covers? Restart Spotify to apply. This is not original Apple Music video artwork.": @"Activer le nouveau style, les commandes rouges, le fond animé et les pochettes en mouvement ? Redémarrez Spotify. Ce ne sont pas les vidéos d’Apple Music.",
            @"Active": @"Actif",
            @"Apply": @"Appliquer",
            @"Sound processing": @"Traitement audio",
            @"Playback speed": @"Vitesse de lecture",
            @"Pitch": @"Hauteur",
            @"Changes playback tempo when available.": @"Change le tempo lorsque disponible.",
            @"Change the sound by semitones.": @"Modifie la hauteur par demi-tons.",
            @"Waiting for audio": @"En attente d’audio",
            @"Available": @"Disponible",
            @"Reset sound changes": @"Réinitialiser le son",
            @"Advanced effects": @"Effets avancés",
            @"JamesDSP equalizer / bass / reverb": @"Égaliseur, basses et réverbération JamesDSP",
            @"Mac build only": @"Version Mac uniquement",
            @"Speed, pitch & haptics": @"Vitesse, tonalité et vibrations",
            @"Theme": @"Thème",
            @"Spotify default": @"Spotify par défaut",
            @"AMOLED black": @"Noir AMOLED",
            @"Apple Music style": @"Style Apple Music",
            @"Midnight blue": @"Bleu nuit",
            @"Violet": @"Violet",
            @"1 source": @"1 source",
            @"%lu sources": @"%lu sources",
            @"Lyrics where Spotify has none": @"Paroles absentes de Spotify",
            @"Search your selected sources for missing lyrics.": @"Chercher des paroles dans les sources sélectionnées.",
            @"Test lyrics for current song": @"Tester les paroles du titre en cours",
            @"Lyrics source test": @"Test des sources de paroles",
            @"No lyrics sources": @"Aucune source de paroles",
            @"No lyrics found for this track from the selected sources.": @"Aucune parole trouvée dans les sources sélectionnées pour ce titre.",
            @"Show source": @"Afficher la source",
            @"Simulate word timing": @"Simuler les mots synchronisés",
            @"Text sizes": @"Tailles du texte",
            @"Translation language": @"Langue de traduction"
        }
        };
    });
    return translations[code][english] ?: english;
}
